function [plateSumm,D,assayTime,Trinity] = trinitySummary(pMWTp,start,finish,varargin)


%% get data from trinitySummary (adjust tap time to middle)
% tap will start in the middle (total column/2)+1
% REQUIRE:
%     - trinity.(wormid).dat files already generated by chor (otrinity =
%     '-O trinity -N all -o nNss*b12xyMmeSakcr'; )
%
% INPUT
%     pMWTp = path to pMWT analysis file containing trinitySummary
%     finish = finish time
%     start = start time
%     frameInt = 0.2 (default)
%     saveoption = 1 (default), 0 = don't save
%     cleanup = 1, will delete .trininty.*.dat file if trinintySummary.mat is found
%
% OUTPUT: 
%     plateSumm;
%     A = structural array containing:
%         A.wormID = wormID; 
%         A.frametime = frameTimeRecord;
%         A.data = plateSumm;
%         A.pMWT = pMWTp;


%% FUNCTION PATHS
% general home path
pMatFun = '/Users/connylin/Dropbox/Code/Matlab';
pRLFun = '/Users/connylin/Dropbox/RL/Code/Modules';
% add packges
addpath([pMatFun,'/General']);
addpath([pRLFun,'/Graphs']);
addpath([pRLFun,'/Graphs/rasterPlot_colorSpeed']);
%% DEFAULTS 
nInput = 3;
frameInt = 0.2; % probably the lowest one can go
saveoption = 0;
cleanup = 1;
%% VARARGIN PROCESSOR
if nargin > nInput
    A = varargin;
    if isinteger(numel(A)/2) == 1
        error('variable entries incorrect')
    end
    callName = A(1:2:numel(A));
    % check if call names are strings
    for x = 1:numel(callName)
       if ischar(callName{x}) == 0
           error('varargin incorrect');
       end
    end
    % get values
    setValue = A(2:2:numel(A));
    for x = 1:numel(callName)
        % determine input type
        if eval(sprintf('ischar(%s)',callName{x})) == 1
            eval(sprintf('%s = ''%s'';',callName{x},setValue{x}));
        elseif eval(sprintf('isnumeric(%s)',callName{x}))
            eval(sprintf('%s = %d;',callName{x},cell2mat(setValue(x))));
        elseif eval(sprintf('iscell(%s)',callName{x}))
            a = setValue{x};
            eval(sprintf('%s = a;',callName{x}));
        else
            error('need coding');
        end
    end
end
%% VARIABLE CONFIRM
if start > finish
    error('start time can not be earlier than finish time');
end


%% (suspend) determine tap time for this pMWT plate
% trininty.dat files contains tap info
%
% [~,f] = fileparts(pMWTp);
% % construct .dat file name
% [~,pset] = dircontent(pMWTp,'*.set');
% p = char(pset);
% % get prefix of .set file
% [~,f] = fileparts(p);
% if numel(p) == 0 % if no tap time data is found, stop using this plate
%     fprintf('No .dat file found in [%s]\n',f);
%     return
% else 
%     if numel(p)> 1; 
%         error('more than one .dat file found'); 
%     elseif numel(p) == 0
%         error('no .dat file was found');
%     end
%     a = dlmread(char(p));
%     if size(a,2) == 4 % sometimes tap time can be at column 4
%         t = a(a(:,4) == 1,1); % find tap time
%     else
%         t = a(a(:,7) == 1,1); % find tap time
%     end
% end


%% find and load trinity summary file, optional clean up
if isempty(dircontent(pMWTp,'trinitySummary.mat')) == 0
    D = load([pMWTp,'/trinitySummary.mat'],'masterData'); D = D.masterData;
    if cleanup == 1
       [~,p] = dircontent(pMWTp,'*trinity.*.dat'); 
       if isempty(p) == 0
           fprintf('cleaning up trinity.*.dat file\n');
           cellfun(@delete,p);
       end
    end
else
   fprintf('no trinitySummary.mat file found\n');
   [~,p] = dircontent(pMWTp,'*trinity.*.dat'); 
   if isempty(p) == 0
        convertTrinityDat2Mat(pMWT);
   else
       error('no trinity.*.dat file found, need to chor\n');
   end
end
Trinity = D;

%% calculate assay time
% tap time is indicated as colume 7 == 1, time is at column 1
% find tap time
a = 0;
t = [];
for wi = 1:size(D,1)
    i = D{wi,2}(:,7) ==1;
    if  sum(i) > 0
        t = [t; D{wi,2}(i,1)];
    end
end
tapTime = unique(t);
if isempty(tapTime) == 0 % if tap is found
    % find taps within start and finish time
    t = tapTime;
    i = t > start & t < finish;
    t = t(i);
    if isempty(t) == 0 % if one or more tap is found, 
        % align to the first tap
        tstart = t(1);
        assayTime = [flip(tstart-frameInt:-frameInt:start)  tstart:frameInt:finish+frameInt];
    elseif sum(i) == 0 % if no tap found in the time frame, 
        % align to first tap
        df = tapTime(1) - floor(tapTime(1));
        tstart = start + df;
        assayTime = [flip(tstart-frameInt:-frameInt:start)  tstart:frameInt:finish+frameInt];
    end
else % if no tap is found
    assayTime = start:frameInt:finish;
end


% (junk potentially) summarize speed info from trinitySummary
% set up array 
% wormcount = 1;
% fMWT = cell(1,1);         
% wormIDRecord = cell(1,1);
% plateSumm = nan(size(D,1),numel(assayTime)-1);
% wormID = D(:,1);
% wormIDVal = false(size(D,1),1);
% frameTimeRecord = nan(size(D,1),numel(assayTime)-1);

%% get column 1(time), 4(speed), 6(bias)
% get size
d = D(:,2);
[r,~] = cellfun(@size,d);
A = nan(sum(r),4);
r1 = 1;
for x = 1:size(D,1)
    r2 = r1+r(x)-1;
    A(r1:r2,1) = repmat(str2num(D{x,1}), r(x),1);
    A(r1:r2,2) = D{x,2}(:,1);
    A(r1:r2,3) = D{x,2}(:,4);
    A(r1:r2,4) = D{x,2}(:,6);
    r1 = r2+1;
end
% remove speed = nan and bias == nan data
A(isnan(A(:,3)) | isnan(A(:,4)),:) = [];

% convert to table;
A = array2table(A,'VariableNames',{'wormid','time','speed','bias'});
DataAll = A;


%% survey times
%  PROBLEM: bias can be -1, 1, or 0. 
% check if nan for bias
D = DataAll;
if sum(isnan(D.bias)) > 0
    error('some bias record are NaN');
end
% delete data outside of assay times
D(D.time < assayTime(1) | D.time >= assayTime(end),:) = []; 


%% translate frametime(ft) into assay times
ft = D.time;
for ti = 1:numel(assayTime)-1
%     if ti == numel(assayTime)
%         i = ft >= assayTime(ti);
%     else
        i = ft >= assayTime(ti) & ft < assayTime(ti+1);
%     end
    if sum(i) == 0
       [~,fn] = fileparts(pMWTp);
       plateSumm = [];
       warning('time point (%.2fs) in plate [%s] has no data, skip',assayTime(ti),fn); 
       return
    end
    ft(i) = assayTime(ti);
end
% validate:
% 1. all frame time must equal to one of the assay time
% 2. number of unique frame time must equal to (assay time -1)
if sum(ismember(ft,assayTime)) ~= numel(ft) ||...
        numel(unique(ft)) ~= numel(assayTime)-1
    error('frame time matching failed');
else
    D.frametime = ft;
end

%% all worms must exist throughout the period
widU = unique(D.wormid);
t1 = assayTime(1);
t2 = assayTime(end-1);
n = nan(numel(widU),1);
nV = (numel(assayTime)-1);
for wi = 1:numel(widU)
    i = D.wormid == widU(wi);
    t = D.frametime(i);
    n = numel(unique(t));
    if n~=nV
        D(i,:) = []; % delete
    end
end

%% average speed * bias per frametimes(ftU)
% PROBLEM: sometimes speed has value as large as 1.32 but bias is 0. What
% does that mean?
% calculate speed dir
D.speedDir = D.speed.*D.bias;
wormidU = unique(D.wormid);
Nwormid = numel(wormidU);
ftU = unique(D.frametime);
A = nan(Nwormid,numel(ftU));
for x = 1:numel(ftU)
    t = ftU(x);

    for wi = 1:numel(wormidU)
        d = D(D.frametime == t & D.wormid == wormidU(wi),:);
        if sum(diff(d.bias)) == 0 
        % if move within this frame all in one dir
        % calculate mean of all data
            A(wi,x) = mean(d.speedDir);
        elseif sum(diff(d.bias)) ~= 0 
        % if movement within this frame contains dir shift
            if sum(d.bias < 0) > 0
            % if reversal exists, only calculate reversal mean
                A(wi,x) = mean(d.speedDir(d.bias < 0));
            elseif sum(d.bias > 0) > 0
            % if only forward exists, only calculate forward mean
                A(wi,x) = mean(d.speedDir(d.bias > 0));
            elseif sum(d.bias == 0) > 0
            % if only bias == 0 (presumably pause), only calculate pase
            % speedDir, which is set to zero
                A(wi,x) = mean(d.speedDir(d.bias == 0));
            end
        end
    end
end
plateSumm = A;
% if any nan results, flag
if sum(any(isnan(A))) > 0
   error('some nan results, code to fix'); 
end



% 
% %%
% for wormi = 1:size(D,1);
%     storedData = D{wormi,2}; % get data from current worm
%     % if current trinity file contains data within start-finish
%     if storedData(1,1) < start && storedData(end,1) > finish;
%         wormIDVal(wormi) = true; % mark worm Id as valid
%         
%         % calculate data
%         % delete data outside of start-finish
%         storedData(storedData(:,1) < assayTime(1) | storedData(:,1) > assayTime(end),:)=[]; 
%         % calculate speed by speed(s) in 4th column x bias (b) in 6th column
%         speedDir = storedData(:,4) .* storedData(:,6); 
%         % translate frametime into assay times
%         ft = storedData(:,1);
%         for ti = 1:numel(assayTime)
%             if ti == numel(assayTime)
%                 i = ft >= assayTime(ti);
%             else
%                 i = ft >= assayTime(ti) & ft < assayTime(ti+1);
%             end
%             ft(i) = assayTime(ti);
%         end
%         % validate
%         if sum(ismember(ft,assayTime)) ~= numel(ft)
%             error('time matching failed')
%         end
% 
%         % average speed per frameTimes
%         frameTimesU = unique(ft);
%         if numel(frameTimesU) == numel(assayTime)-1
%             frameTimeRecord(wormi,:) = frameTimesU;
%             movemeans = nan(size(frameTimesU));
%             movedir  = nan(size(frameTimesU)); 
%             for jj = 1:numel(frameTimesU) % repeat for frame time
%                 rowIndx = ft == frameTimesU(jj);
%                 if abs(sum(speedDir(rowIndx,1))) == sum(abs(speedDir(rowIndx,1))); % if all movements within this frame range is in the same direction
%                     rowN = sum(rowIndx);
%                     movedir(jj)  = rowN>1; 
%                     movemeans(jj) = sum(speedDir(rowIndx,1))/rowN;
%                 else % if movement are different directions within frame, only calculate reversal mean
%                     conN = speedDir(rowIndx,1)<0; % get reversal 
%                     movemeans(jj) = sum(speedDir(conN,1))/sum(conN); 
%                 end
%             end
%             plateSumm(wormi,:) = movemeans';
%         end
%     end
% end
% % remove nan results
% i = any(isnan(plateSumm),2);
% plateSumm(i,:) = [];
% frameTimeRecord(i,:) = [];
% wormID(i) = [];
% wormID = str2num(char(wormID));


%% output
% create output structure array
% A = struct;
% A.wormID = wormID;
% A.frametime = frameTimeRecord;
% A.data = plateSumm;
% A.pMWT = pMWTp;

% text output
if saveoption == 1
    dlmwrite(sprintf('%s/%ds_%ds_fint_%.1f_N%d_wormID.trinitySummary',pMWTp,start,finish,frameInt,size(wormID,1)),wormID);
    dlmwrite(sprintf('%s/%ds_%ds_fint_%.1f_N%d_frametime.trinitySummary',pMWTp,start,finish,frameInt,size(wormID,1)),frameTimeRecord)
    dlmwrite(sprintf('%s/%ds_%ds_fint_%.1f_N%d_rasterdata.trinitySummary',pMWTp,start,finish,frameInt,size(wormID,1)),plateSumm)
end

