function figure1 = createfigure_rType(X, Y, E, gn, strain, respType,varargin)
%CREATEFIGURE(XMATRIX1, YMATRIX1, EMATRIX1)
%  XMATRIX1:  errorbar x matrix
%  YMATRIX1:  errorbar y matrix
%  EMATRIX1:  errorbar e matrix

%  Auto-generated by MATLAB on 10-Oct-2016 17:03:58
%% graphSetType
color = [0 0 0; 1 0 0;...
[0 0.447058826684952 0.74117648601532];    
[0.494117647409439 0.184313729405403 0.556862771511078]
    ];
marker = {'none';'none';'none';'none'};
vararginProcessor;

%% -----------------------------------
    
% Create figure
figure1 = figure('Visible','off');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple error bars using matrix input to errorbar
errorbar1 = errorbar(X,Y,E);
for gi = 1:numel(gn)
    set(errorbar1(gi),...
        'Color',color(gi,:),...
        'DisplayName',regexprep(gn{gi},'_',' '),...
        'Marker',marker{gi})
end

title(strain)
% Create xlabel
xlabel('time(s)');
xlim([0.05 0.51])

% Create ylabel
yname = sprintf('P (%s/responses)',respType);
ylabel(yname);
ylim([0 1])


